# Generated by Django 3.2.13 on 2022-06-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bill_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsfile',
            name='name',
            field=models.FileField(upload_to='bills/'),
        ),
        migrations.AlterField(
            model_name='clientorgsfile',
            name='name',
            field=models.FileField(upload_to='clients/'),
        ),
    ]
