# Generated by Django 3.2.13 on 2022-07-01 13:51

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220630_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsfile',
            name='name',
            field=models.FileField(upload_to='bills/', validators=[api.validators.validate_upload_file]),
        ),
        migrations.AlterField(
            model_name='clientorgsfile',
            name='name',
            field=models.FileField(upload_to='clients/', validators=[api.validators.validate_upload_file]),
        ),
    ]
