# Generated by Django 3.2.13 on 2022-07-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220701_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_field_name', models.CharField(blank=True, max_length=50, null=True)),
                ('org_field_name', models.CharField(blank=True, max_length=50, null=True)),
                ('number_field_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sum_field_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_field_name', models.CharField(blank=True, max_length=50, null=True)),
                ('service_field_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
